import os
import json
import logging
from typing import Dict, List
from ml.training.training_config import TrainingConfig
from ml.training.training_utils import compute_file_sha256

logger = logging.getLogger("model_training_pipeline")

class HashGenerator:
    """
    Computes SHA-256 checksums of trained model binaries, metadata files,
    registry index, and execution logs, storing digests under hashes/.
    """
    def __init__(self, config: TrainingConfig) -> None:
        self.config = config

    def generate_model_hashes(self, model_name: str, file_paths: Dict[str, str]) -> str:
        """
        Computes SHA-256 hashes for the files generated by a trainer (model, config, features, metadata).
        Saves the hashes to <hashes_dir>/<model_name>_hashes.json.
        
        Returns:
            The path of the generated hashes file.
        """
        hashes_dir = self.config.get_output_dir("hashes_dir")
        os.makedirs(hashes_dir, exist_ok=True)
        
        hashes_data = {}
        for key, path in file_paths.items():
            if os.path.exists(path):
                file_hash = compute_file_sha256(path)
                hashes_data[file_hash] = path  # Key is hash, value is path
                
        hash_file_path = os.path.join(hashes_dir, f"{model_name}_hashes.json")
        try:
            with open(hash_file_path, "w", encoding="utf-8") as f:
                json.dump(hashes_data, f, indent=4)
            logger.info(f"Generated model hashes for '{model_name}' at {hash_file_path}")
        except Exception as e:
            logger.error(f"Failed to save model hashes for {model_name}: {e}")
            raise
            
        return hash_file_path

    def generate_pipeline_hashes(self, file_paths: Dict[str, str]) -> str:
        """
        Computes SHA-256 hashes for general pipeline outputs (registry, statistics, report, versions).
        Saves the hashes to <hashes_dir>/pipeline_hashes.json.
        
        Returns:
            The path of the generated hashes file.
        """
        hashes_dir = self.config.get_output_dir("hashes_dir")
        os.makedirs(hashes_dir, exist_ok=True)
        
        hashes_data = {}
        for key, path in file_paths.items():
            if os.path.exists(path):
                file_hash = compute_file_sha256(path)
                hashes_data[file_hash] = path
                
        hash_file_path = os.path.join(hashes_dir, "pipeline_hashes.json")
        try:
            with open(hash_file_path, "w", encoding="utf-8") as f:
                json.dump(hashes_data, f, indent=4)
            logger.info(f"Generated pipeline hashes at {hash_file_path}")
        except Exception as e:
            logger.error(f"Failed to save pipeline hashes: {e}")
            raise
            
        return hash_file_path
