import os
import json
import logging
import hashlib
import pandas as pd
from typing import Dict, Any, List, Tuple

logger = logging.getLogger("admin_review_pipeline")

class AdminReviewOutputsValidator:
    """
    AdminReviewOutputsValidator verifies that all files generated by the admin review system
    are structurally correct, exist, are non-empty, and match their recorded SHA-256 hashes.
    """
    def __init__(self, config) -> None:
        self.config = config

    def calculate_sha256(self, filepath: str) -> str:
        """Helper to calculate SHA-256 hash of a file."""
        if not os.path.exists(filepath):
            return ""
        sha256 = hashlib.sha256()
        with open(filepath, "rb") as f:
            while chunk := f.read(8192):
                sha256.update(chunk)
        return sha256.hexdigest()

    def validate_outputs(self) -> Tuple[bool, List[str]]:
        """
        Validates the output files.
        Returns a tuple: (is_valid: bool, errors: List[str])
        """
        errors = []

        # 1. File existence and size checks
        files_to_check = [
            ("Review History CSV", self.config.get_path("admin_review_history_csv")),
            ("Approved Feedback CSV", self.config.get_path("approved_feedback_csv")),
            ("Statistics JSON", self.config.get_path("admin_review_statistics_json")),
            ("Metadata JSON", self.config.get_path("admin_review_metadata_json")),
            ("Report Markdown", self.config.get_path("admin_review_report_md")),
            ("Hashes JSON", self.config.get_path("admin_review_hashes_json")),
            ("Versions JSON", self.config.get_path("admin_review_versions_json"))
        ]

        for label, filepath in files_to_check:
            if not os.path.exists(filepath):
                errors.append(f"{label} is missing at '{filepath}'.")
            elif os.path.getsize(filepath) == 0:
                errors.append(f"{label} file at '{filepath}' is empty.")

        if errors:
            return False, errors

        # 2. Check Review History CSV Columns
        try:
            df_history = pd.read_csv(self.config.get_path("admin_review_history_csv"))
            expected_history_cols = ["Feedback ID", "Review Status", "Reviewer", "Review Notes", "Timestamp"]
            for col in expected_history_cols:
                if col not in df_history.columns:
                    errors.append(f"Review History CSV is missing column '{col}'.")
        except Exception as e:
            errors.append(f"Failed to load or parse Review History CSV: {e}")

        # 3. Check Approved Feedback CSV Columns & Integrity (only APPROVED feedback allowed)
        try:
            df_approved = pd.read_csv(self.config.get_path("approved_feedback_csv"))
            if not df_approved.empty:
                expected_approved_cols = ["Feedback ID", "Timestamp", "Prediction", "Verification", "Decision", "Feedback", "Comment"]
                for col in expected_approved_cols:
                    if col not in df_approved.columns:
                        errors.append(f"Approved Feedback CSV is missing column '{col}'.")
                
                # Check that every ID in approved_feedback.csv is indeed approved in history
                if os.path.exists(self.config.get_path("admin_review_history_csv")):
                    df_hist = pd.read_csv(self.config.get_path("admin_review_history_csv"))
                    # Group by ID and find latest status
                    latest_states = {}
                    for _, row in df_hist.iterrows():
                        latest_states[row["Feedback ID"]] = row["Review Status"]
                    
                    for approved_id in df_approved["Feedback ID"]:
                        status = latest_states.get(approved_id)
                        if status != "APPROVED":
                            errors.append(f"Approved feedback dataset contains Feedback ID '{approved_id}' but its latest history status is '{status}'.")
        except Exception as e:
            errors.append(f"Failed to load or parse Approved Feedback CSV: {e}")

        # 4. Check Statistics JSON schema
        try:
            with open(self.config.get_path("admin_review_statistics_json"), "r", encoding="utf-8") as f:
                stats = json.load(f)
            required_stats_keys = ["total_reviews", "approved_count", "rejected_count", "pending_count", "approval_rate"]
            for rk in required_stats_keys:
                if rk not in stats:
                    errors.append(f"Statistics JSON is missing key '{rk}'.")
        except Exception as e:
            errors.append(f"Failed to parse Statistics JSON: {e}")

        # 5. Check Metadata JSON schema
        try:
            with open(self.config.get_path("admin_review_metadata_json"), "r", encoding="utf-8") as f:
                metadata = json.load(f)
            required_meta_keys = ["pipeline_name", "pipeline_version", "system_version", "last_executed"]
            for mk in required_meta_keys:
                if mk not in metadata:
                    errors.append(f"Metadata JSON is missing key '{mk}'.")
        except Exception as e:
            errors.append(f"Failed to parse Metadata JSON: {e}")

        # 6. Check Versions JSON structure
        try:
            with open(self.config.get_path("admin_review_versions_json"), "r", encoding="utf-8") as f:
                versions = json.load(f)
            if not isinstance(versions, list):
                errors.append("Versions JSON must be a list of snapshots.")
        except Exception as e:
            errors.append(f"Failed to parse Versions JSON: {e}")

        # 7. Integrity validation using recorded SHA-256 hashes
        try:
            with open(self.config.get_path("admin_review_hashes_json"), "r", encoding="utf-8") as f:
                registered_hashes = json.load(f)
            
            # We check the hashes of all tracked files
            files_to_hash_check = {
                "history": self.config.get_path("admin_review_history_csv"),
                "approved": self.config.get_path("approved_feedback_csv"),
                "statistics": self.config.get_path("admin_review_statistics_json"),
                "metadata": self.config.get_path("admin_review_metadata_json"),
                "report": self.config.get_path("admin_review_report_md"),
                "versions": self.config.get_path("admin_review_versions_json")
            }

            for key, filepath in files_to_hash_check.items():
                if key in registered_hashes:
                    actual_hash = self.calculate_sha256(filepath)
                    recorded_hash = registered_hashes[key]
                    if actual_hash != recorded_hash:
                        errors.append(f"Hash mismatch for '{key}' file. Expected: '{recorded_hash}', Actual: '{actual_hash}'.")
                else:
                    errors.append(f"Hashes registry is missing entry for '{key}'.")
        except Exception as e:
            errors.append(f"Failed to complete SHA-256 hash checks: {e}")

        # 8. Check charts existence
        if self.config.enable_charts:
            charts_to_check = [
                ("Approval Distribution Chart", os.path.join(self.config.get_path("charts_dir"), "approval_distribution.png")),
                ("Review Status Distribution Chart", os.path.join(self.config.get_path("charts_dir"), "review_status_distribution.png"))
            ]
            for label, filepath in charts_to_check:
                if not os.path.exists(filepath):
                    errors.append(f"{label} file is missing at '{filepath}'.")
                elif os.path.getsize(filepath) == 0:
                    errors.append(f"{label} file at '{filepath}' is empty.")

        return len(errors) == 0, errors
