# Import the Base and all models so that Alembic can detect them
# and include them in autogenerated migrations.

from app.database.database import Base  # noqa
from app.database.models.user import User  # noqa
from app.database.models.dataset import Dataset  # noqa
from app.database.models.model_version import ModelVersion  # noqa
from app.database.models.prediction import Prediction  # noqa
from app.database.models.live_verification import LiveVerification  # noqa
from app.database.models.feedback import Feedback  # noqa
from app.database.models.verification_queue import VerificationQueue  # noqa
from app.database.models.approved_dataset import ApprovedDataset  # noqa
